Add short path for LinearOperator.repeat()
cornellius-gp/linear_operator pull request #70
Opened 2023-06-08 12:08 UTC by Turakar

This adds a short path for LinearOperator.repeat() if we would otherwise create a new `BatchRepeatLinearOperator` which would be a no-op.

`repeat()` is called like this for example by the constructor of `KroneckerProductLinearOperator`.

By reducing one level of indirection, we gain two benefits: a) slightly better performance (obviously), and b) some more optimizations by calling native functions instead of default `LinearOperator` functions, e.g. for `_diagonal()`.

2023-06-08 15:05 UTC, Balandat reviewed
This makes sense to me. Should we add a unit test for this to check that we indeed return the same object rather than a `BatchRepeatLinearOperator` in this case?

2023-07-06 18:23 UTC, gpleiss requested changes
@Turakar please add a unit test like @Balandat suggests, and then we'll merge!

2023-07-07 06:49 UTC, Turakar commented
Seems like there were no unit tests before, so I added tests for both cases: A No-Op case and a true case. I also allowed the `repeat(1, 1)` case as this is a no-op, too.

2023-07-15 18:32 UTC, Balandat approved these changes

2023-07-15 18:53 UTC, merged